version: '2'
services:
  app:
    container_name: dominenv_app
    build:
      context: ./
      dockerfile: php/php.dockerfile
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    user: "${USER_ID}"
    environment:
      - "USER_ID=${USER_ID}"
    networks:
      - application
    ports:
      - 9000
    tty: true

  nginx:
    container_name: dominenv_nginx
    image: nginx:1
    working_dir: /var/www
    volumes_from:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/vhost.conf:/etc/nginx/vhost.conf
    ports:
      - 8080:80
    environment:
      - "USER_ID=${USER_ID}"
    networks:
      - application

  mysql:
    container_name: dominenv_mysql
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
        - "33061:3306"
    environment:
      - "USER_ID=${USER_ID}"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    networks:
      - application

volumes:
  mysql_data:

networks:
  application:
